### ISSUE TITLE
ToDo's: update filepaths

### ISSUE THREAD

**Issue by A-Buch** [A-Buch/flood-loss-models-4-HCMC#1]
ToDo:

- [x]  update filepaths for feature selection scripts (# [47ec25b](https://github.com/A-Buch/flood-loss-models-4-HCMC/commit/47ec25b4709a10f978c6ca4732a00b6dd748e6ae))
- [ ]  update filepaths for Bayesian Network scripts
- [ ] update filepaths for data preprocessing script
