### ISSUE TITLE
ToDo's: health paper

### ISSUE THREAD

**Issue by A-Buch** [A-Buch/flood-loss-models-4-HCMC#2]
ToDo's:

- [ ] make updates as new branch, incl only feature selection models, replace CRF by simple RF model

 update partial dependence plots 
- [ ] plot only 5 features, adapt figure size
- [ ]  get rid of the ticks/labels on the outer frame 
- [ ] increase size of the legend
