### ISSUE TITLE
ToDo's: branch with example dataset

### ISSUE THREAD

**Issue by A-Buch** [A-Buch/flood-loss-models-4-HCMC#3]
- [ ]  update descriptions in BN files
- [ ]  update analysis and descriptions in BN notebook files

optional:
- [ ] test widgets for jupyter notebooks - interactive adaption of BN structure
